Sample_MVCECommerce/ECommerce/Models/ErrorViewModel.cs
using System;

namespace ECommerce.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sample_MVCECommerce/ECommerce/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using EntityLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Linq;

namespace ECommerce.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new CategoryDal());
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var values = cm.GetAllCategory();
            return View(values);
        }
        [HttpGet]
        public IActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Category category)
        {
            cm.AddCategory(category);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Guncelle(int id)
        {
            using (Context c = new Context())
            {
                var result = c.Categories.FirstOrDefault(o => o.category_Id == id);
                return View(result);
            }
        }
        [HttpPost]
        public IActionResult Guncelle(Category category)
        {
            var result = cm.UpdateCategory(category);

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Sil(int id)
        {
            using (Context db = new Context())
            {
                var result = db.Categories.FirstOrDefault(o => o.category_Id == id);
                db.Categories.Remove(result);
                db.SaveChanges();
            }

            return RedirectToAction("Index");

        }
















        public IActionResult KategoriEkle()
        {
            return View();
        }
    }
}

Sample_MVCECommerce/ECommerce/Controllers/HomeController.cs
using BusinessLayer.Abstract;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
     
    }
}

Sample_MVCECommerce/ECommerce/Controllers/TagController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using EntityLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Linq;

namespace ECommerce.Controllers
{
    public class TagController : Controller
    {
        TagManager tm = new TagManager(new TagDal());
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var values = tm.GetAllTag();
            return View(values);
        }
        [HttpGet]
        public IActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Tag tag)
        {
            tm.AddTag(tag);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Guncelle(int id)
        {
            using (Context c = new Context())
            {
                var result = c.Tags.FirstOrDefault(o => o.tag_ID == id);
                return View(result);
            }
        }
        [HttpPost]
        public IActionResult Guncelle(Tag tag)
        {
            var result = tm.UpdateTag(tag);

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Sil(int id)
        {
            using (Context db = new Context())
            {
                var result = db.Tags.FirstOrDefault(o => o.tag_ID == id);
                db.Tags.Remove(result);
                db.SaveChanges();
            }

            return RedirectToAction("Index");

        }



























        /*public IActionResult Index()
        {
            return View();
        }
        */
    }
}

Sample_MVCECommerce/ECommerce/Controllers/UserController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using EntityLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Linq;

namespace ECommerce.Controllers
{
    public class UserController : Controller
    {
        UserMan um = new UserMan(new UserRepo());
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var values = um.GetAllUser();
            return View(values);
        }
        [HttpGet]
        public IActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(User user)
        {
            um.AddUser(user);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Guncelle(int id)
        {
            using (Context c = new Context())
            {
                var result = c.users.FirstOrDefault(o => o.UserID == id);

                return View(result);
            }
        }
        [HttpPost]
        public IActionResult Guncelle(User user)
        {
            var result = um.UpdateUser(user);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Sil(int id)
        {
            using (Context db = new Context())
            {
                var result = db.users.FirstOrDefault(o => o.UserID == id);
                db.users.Remove(result);
                db.SaveChanges();
            }

            return RedirectToAction("Index");

        }

        /*public IActionResult Index()
        {
            return View();
        }
        */
    }
}

Sample_MVCECommerce/ECommerce/Views/Admin/Ekle.cshtml
@model EntityLayer.Product
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>YENİ ÜRÜN EKLE</h1>

<form asp-action="Ekle" asp-controller="Admin" method="post">
    <div class="mb-3">
        <label   class="form-label">ÜRÜN ADI</label>
        <input asp-for="product_Name" type="text" class="form-control">

    </div>
    <div class="mb-3">
        <label   class="form-label">ÜRÜN FİYATI</label>
        <input type="text" class="form-control" asp-for="product_Price">
    </div>
    <div class="mb-3">
        <label   class="form-label">ÜRÜN URL </label>
        <input type="text" class="form-control" asp-for="product_Stock">
    </div>
 
    <button type="submit" class="btn btn-primary">ÜRÜN EKLE</button>
</form>

Sample_MVCECommerce/ECommerce/Views/Admin/Guncelle.cshtml
@model EntityLayer.Product
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>ÜRÜN GÜNCELLE</h1>

<form asp-action="Guncelle" asp-controller="Admin" method="post">
    <div style="display:none" class="mb-3">
        <label  class="form-label">ÜRÜN ID </label>
        <input  readonly type="text" class="form-control" asp-for="product_Id">
        </div>
        <div class="mb-3">
        <label  class="form-label"> ÜRÜN ADI</label>
        <input type="text" class="form-control" asp-for="product_Name">
        </div>
    <div class="mb-3">
        <label class="form-label"> ÜRÜN FİYATI</label>
        <input type="text" class="form-control" asp-for="product_Price">
    </div>
    <div class="mb-3">
        <label  class="form-label">ÜRÜN URL </label>
        <input type="text" class="form-control" asp-for="product_Stock">
    </div>
 
    <button type="submit" class="btn btn-primary">ÜRÜN GÜNCELLE </button>
</form>

Sample_MVCECommerce/ECommerce/Views/Admin/Index.cshtml
@using EntityLayer;
@model List<Product>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>ÜRÜN LİSTESİ</h1>
<div><a asp-action="Ekle" asp-controller="Admin" class="btn btn-primary">Ürün ekle</a></div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Default Table</h5>

                    <!-- Default Table -->
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Ürün ID</th>
                                <th scope="col">Ürün Adı</th>
                                <th scope="col">Ürün Fiyatı </th>
                                <th scope="col">Ürün Fotoğraf URL</th>
                                <th scope="col">İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var a in Model)
                            {
                                <tr>
                                    <td>@a.product_Id</td>
                                    <td>@a.product_Name</td>
                                    <td>@a.product_Price</td>
                                    <td>@a.product_Stock</td>
                                    <td>
                                        <a onclick="return confirm('Silmek istediğinize eminmisiniz?');" asp-controller="Admin" asp-action="Sil" asp-route-id="@a.product_Id" class="btn btn-danger">sil</a>

                                        <a asp-controller="Admin" asp-action="Guncelle" asp-route-id="@a.product_Id" class="btn btn-warning">Güncelle</a>
                                    </td>
                                    <td>
                                    </td>


                                </tr>
                            }
                            
                        </tbody>
                    </table>
                    <!-- End Default Table Example -->
                </div>
            </div>

        </div>

    </div>
</section>

Sample_MVCECommerce/ECommerce/Views/Category/Ekle.cshtml
@model EntityLayer.Category
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>Ekle</h1>
<form asp-action="Ekle" asp-controller="Category" method="post">
    <div class="mb-3">
        <label class="form-label">KATEGORİ ADI</label>
        <input asp-for="category_Name" type="text" class="form-control">

    </div>
    <div class="mb-3">
        <label class="form-label">KATEGORİ İÇERİĞİ</label>
        <input type="text" class="form-control" asp-for="category_Content">
    </div>

    <button type="submit" class="btn btn-primary">KATEGORİ EKLE</button>
</form>

Sample_MVCECommerce/ECommerce/Views/Category/Guncelle.cshtml
@model EntityLayer.Category
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>Kategori Guncelle</h1>
<form asp-action="Guncelle" asp-controller="Category" method="post">
    <div style="display:none" class="mb-3">
        <label class="form-label">KATEGORİ ID </label>
        <input readonly type="text" class="form-control" asp-for="category_Id">
    </div>
    <div class="mb-3">
        <label class="form-label">KATEGORİ ADI</label>
        <input type="text" class="form-control" asp-for="category_Name">
    </div>
    <div class="mb-3">
        <label class="form-label">KATEGORİ İÇERİĞİ</label>
        <input type="text" class="form-control" asp-for="category_Content">
    </div>

    <button type="submit" class="btn btn-primary">KATEGORİ GÜNCELLE </button>
</form>

Sample_MVCECommerce/ECommerce/Views/Category/Index.cshtml
@using EntityLayer;
@model List<Category>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>KATEGORİ TABLOSU</h1>
<div><a asp-action="Ekle" asp-controller="Category" class="btn btn-primary">Kategori ekle</a></div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Default Table</h5>

                    <!-- Default Table -->
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Kategori ID</th>
                                <th scope="col">Kategori Adı</th>
                                <th scope="col">Kategori İçeriği </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var a in Model)
                            {
                                <tr>
                                    <td>@a.category_Id</td>
                                    <td>@a.category_Name</td>
                                    <td>@a.category_Content</td>
                                    <td>
                                        <a onclick="return confirm('Silmek istediğinize eminmisiniz?');" asp-controller="Category" asp-action="Sil" asp-route-id="@a.category_Id" class="btn btn-danger">sil</a>

                                        <a asp-controller="Category" asp-action="Guncelle" asp-route-id="@a.category_Id" class="btn btn-warning">Güncelle</a>
                                    </td>
                                    <td>
                                    </td>


                                </tr>
                            }

                        </tbody>
                    </table>
                    <!-- End Default Table Example -->
                </div>
            </div>

        </div>

    </div>
</section>

Sample_MVCECommerce/ECommerce/Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>ADMİN PANEL</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/NiceAdmin/assets/img/favicon.png" rel="icon">
  <link href="~/NiceAdmin/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/NiceAdmin/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/NiceAdmin/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/NiceAdmin/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/NiceAdmin/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/NiceAdmin/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/NiceAdmin/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/NiceAdmin/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/NiceAdmin/assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.4.16
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <img src="~/NiceAdmin/assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">ADMIN PANEL</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->



        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="~/NiceAdmin/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">Lütfi Gürses</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Harun Gündoğmuş</h6>
              <h6>Yasin Lütfi Gürses</h6>
              <span>Full-Stack Dev.</span>
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" asp-action="List" asp-controller="ECO">
                <i class="bi bi-box-arrow-right"></i>
                <span>Çıkış Yap</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-layout-text-window-reverse"></i><span>Tables</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-nav" class="nav-content collapse show" data-bs-parent="#sidebar-nav">
          <li>
            <a asp-action="Index" asp-controller="Admin" class="active">
              <i class="bi bi-circle"></i><span>Ürün Tablosu</span>
            </a>
          </li>
          <li>
                        <a asp-action="Index" asp-controller="Tag">
              <i class="bi bi-circle"></i><span>Etiket Tablosu</span>
            </a>
          </li>
          <li>
                        <a asp-action="Index" asp-controller="Category">
              <i class="bi bi-circle"></i><span>Kategori Tablosu</span>
              </a>
          </li>
          <li>
            <a asp-action="Index" asp-controller="User">
              <i class="bi bi-circle"></i><span>Kullanıcı Tablosu</span>
            </a>
          </li>
        </ul>
      </li><!-- End Tables Nav -->




    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>TABLOLAR</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">TABLO</a></li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    @RenderBody();

  </main><!-- End #main -->
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>ADMIN DASHBOARD</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/NiceAdmin/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/NiceAdmin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/NiceAdmin/assets/vendor/chart.js/chart.min.js"></script>
  <script src="~/NiceAdmin/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/NiceAdmin/assets/vendor/quill/quill.min.js"></script>
  <script src="~/NiceAdmin/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/NiceAdmin/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/NiceAdmin/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/NiceAdmin/assets/js/main.js"></script>

</body>

</html>

Sample_MVCECommerce/ECommerce/Views/Tag/Ekle.cshtml
@model EntityLayer.Tag
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>ETİKET EKLE</h1>
<form asp-action="Ekle" asp-controller="Tag" method="post">
    <div class="mb-3">
        <label class="form-label">ETİKET İÇERİĞİ</label>
        <input type="text" class="form-control" asp-for="tag_Name">
    </div>

    <button type="submit" class="btn btn-primary">ETİKET EKLE</button>
</form>

Sample_MVCECommerce/ECommerce/Views/Tag/Guncelle.cshtml
@model EntityLayer.Tag;
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>ETİKET GÜNCELLE</h1>
<form asp-action="Guncelle" asp-controller="Tag" method="post">
    <div class="mb-3">
        <label class="form-label">ETİKET İÇERİĞİ</label>
        <input type="text" class="form-control" asp-for="tag_Name">
    </div>

    <button type="submit" class="btn btn-primary">ETİKET GÜNCELLE </button>
</form>

Sample_MVCECommerce/ECommerce/Views/Tag/Index.cshtml
@using EntityLayer;
@model List<Tag>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>ETİKET LİSTESİ</h1>
<div><a asp-action="Ekle" asp-controller="Tag" class="btn btn-primary">ETİKET EKLE</a></div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Default Table</h5>

                    <!-- Default Table -->
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Etiket ID</th>
                                <th scope="col">Etiket Adı</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var a in Model)
                            {
                                <tr>
                                    <td>@a.tag_ID</td>
                                    <td>@a.tag_Name</td>
                                    <td>
                                        <a onclick="return confirm('Silmek istediğinize eminmisiniz?');" asp-controller="Tag" asp-action="Sil" asp-route-id="@a.tag_ID" class="btn btn-danger">sil</a>

                                        <a asp-controller="Tag" asp-action="Guncelle" asp-route-id="@a.tag_Name" class="btn btn-warning">Güncelle</a>
                                    </td>
                                    <td>
                                    </td>


                                </tr>
                            }

                        </tbody>
                    </table>
                    <!-- End Default Table Example -->
                </div>
            </div>

        </div>

    </div>
</section>

Sample_MVCECommerce/ECommerce/Views/User/Ekle.cshtml
@model EntityLayer.User
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>YENİ KULLANICI EKLE</h1>
<form asp-action="Ekle" asp-controller="User" method="post">
    <div class="mb-3">
        <label class="form-label">KULLANICI ADI</label>
        <input asp-for="Username" type="text" class="form-control">

    </div>
    <div class="mb-3">
        <label class="form-label">KULLANICI ŞİFRESİ</label>
        <input type="text" class="form-control" asp-for="UserPassword">
    </div>
    <div class="mb-3">
        <label class="form-label">KULLANICI ROLÜ</label>
        <input type="text" class="form-control" asp-for="UserRole">
    </div>

    <button type="submit" class="btn btn-primary">KATEGORİ EKLE</button>
</form>

Sample_MVCECommerce/ECommerce/Views/User/Guncelle.cshtml
@model EntityLayer.User
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>KULLANICI GÜNCELLE</h1>
<form asp-action="Guncelle" asp-controller="User" method="post">
    <div class="mb-3">
        <label class="form-label">KULLANICI ADI </label>
        <input readonly type="text" class="form-control" asp-for="Username">
    </div>
    <div class="mb-3">
        <label class="form-label">KULLANICI ŞİFRESİ</label>
        <input type="text" class="form-control" asp-for="UserPassword">
    </div>
    <div class="mb-3">
        <label class="form-label">KULLANICI ROLÜ</label>
        <input type="text" class="form-control" asp-for="UserRole">
    </div>

    <button type="submit" class="btn btn-primary">KULLANICI GÜNCELLE </button>
</form>

Sample_MVCECommerce/ECommerce/Views/User/Index.cshtml
@using EntityLayer;
@model List<User>;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>KULLANICI LİSTESİ</h1>
<div><a asp-action="Ekle" asp-controller="User" class="btn btn-primary">KULLANICI EKLE</a></div>
<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Default Table</h5>

                    <!-- Default Table -->
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Kullanıcı ID</th>
                                <th scope="col">Kullanıcı Adı</th>
                                <th scope="col">Kullanıcı Şifresi </th>
                                <th scope="col">Kullanıcı Rolü</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var a in Model)
                            {
                                <tr>
                                    <td>@a.UserID</td>
                                    <td>@a.Username</td>
                                    <td>@a.UserPassword</td>
                                    <td>@a.UserRole</td>
                                    <td>
                                        <a onclick="return confirm('Silmek istediğinize eminmisiniz?');" asp-controller="User" asp-action="Sil" asp-route-id="@a.UserID" class="btn btn-danger">sil</a>

                                        <a asp-controller="User" asp-action="Guncelle" asp-route-id="@a.UserID" class="btn btn-warning">Güncelle</a>
                                    </td>
                                    <td>
                                    </td>


                                </tr>
                            }

                        </tbody>
                    </table>
                    <!-- End Default Table Example -->
                </div>
            </div>

        </div>

    </div>
</section>